using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AppleReceiptVerifier.NET.Models
{
    /// <summary>
    /// The decoded version of the encoded receipt data sent with the request to the App Store.
    /// </summary>
    /// <param name="AdamId">See <see cref="AppleReceiptVerifier.NET.Models.Receipt.AppItemId"/>.</param>
    /// <param name="AppItemId">Generated by App Store Connect and used by the App Store to uniquely identify the app purchased. Apps are assigned this identifier only in production.</param>
    /// <param name="ApplicationVersion">The app’s version number. The app's version number corresponds to the value of <i>CFBundleVersion</i> (in iOS) or <i>CFBundleShortVersionString</i> (in macOS) in the <i>Info.plist</i>. 
    /// In production, this value is the current version of the app on the device based on the <i>receipt_creation_date_ms</i>. In the sandbox, the value is always <b>1.0</b>.</param>
    /// <param name="BundleId">The bundle identifier for the app to which the receipt belongs. You provide this string on App Store Connect. This corresponds to the value of <i>CFBundleIdentifier</i> in the <i>Info.plist</i> file of the app.</param>
    /// <param name="DownloadId">A unique identifier for the app download transaction.</param>
    /// <param name="ExpirationDate">The time the receipt expires for apps purchased through the Volume Purchase Program. If this key is not present for apps purchased through the Volume Purchase Program, the receipt does not expire.</param>
    /// <param name="InApp">An array that contains the in-app purchase receipt fields for all in-app purchase transactions. <a href="https://developer.apple.com/documentation/appstorereceipts/responsebody/receipt/in_app">(docs)</a></param>
    /// <param name="OriginalApplicationVersion">The version of the app that the user originally purchased. This value does not change, 
    /// and corresponds to the value of <i>CFBundleVersion</i> (in iOS) or <i>CFBundleShortVersionString</i> (in macOS) in the <i>Info.plist file of the original purchase. In the sandbox environment, the value is always "1.0".</param>
    /// <param name="OriginalPurchaseDate">The time of the original app purchase.</param>
    /// <param name="PreorderDate">The time the user ordered the app available for pre-order. This field is only present if the user pre-orders the app.</param>
    /// <param name="ReceiptCreationDate">The time the App Store generated the receipt. This value does not change.</param>
    /// <param name="ReceiptType">The type of receipt generated. The value corresponds to the environment in which the app or VPP purchase was made.</param>
    /// <param name="RequestDate">The time the request to the <i>verifyReceipt</i> endpoint was processed and the response was generated.</param>
    /// <param name="VersionExternalIdentifier">An arbitrary number that identifies a revision of your app. In the sandbox, this key's value is <b>0</b>.</param>
    public record Receipt(long AdamId, long AppItemId, string ApplicationVersion, string BundleId,
        long DownloadId, DateTimeOffset? ExpirationDate, InApp[] InApp, string OriginalApplicationVersion,
        DateTimeOffset OriginalPurchaseDate, DateTimeOffset? PreorderDate, DateTimeOffset ReceiptCreationDate, string ReceiptType,
        DateTimeOffset RequestDate, int VersionExternalIdentifier);

    /// <summary>
    /// The type of receipt generated. The value corresponds to the environment in which the app or VPP purchase was made.
    /// </summary>
    public enum ReceiptType
    {
        Production,
        ProductionVPP,
        ProductionSandbox,
        ProductionVPPSandbox
    }
}
