name: publish to nuget
on:
  release:
    types: [published]
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to NuGet
        run: |
          dotnet pack -c Release --include-source --include-symbols --nologo -o ./packed
          dotnet nuget push "./packed/*" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
